import type { Track } from "./types";

export const mockTracks: Track[] = [
  {
    id: "midnight-city",
    title: "Midnight City",
    artist: "M83",
    album: "Hurry Up, We're Dreaming",
    duration: "4:03",
    bpm: 105,
    matchPercent: 96,
    mood: "late night",
    accent: "#7b5cff",
    secondaryAccent: "#f064a4",
  },
  {
    id: "sweet-disposition",
    title: "Sweet Disposition",
    artist: "The Temper Trap",
    album: "Conditions",
    duration: "3:54",
    bpm: 129,
    matchPercent: 91,
    mood: "dance",
    accent: "#24c6dc",
    secondaryAccent: "#514a9d",
  },
  {
    id: "borderline",
    title: "Borderline",
    artist: "Tame Impala",
    album: "The Slow Rush",
    duration: "3:57",
    bpm: 97,
    matchPercent: 88,
    mood: "chill",
    accent: "#ff9a8b",
    secondaryAccent: "#ff6a88",
  },
  {
    id: "telepatia",
    title: "telepatia",
    artist: "Kali Uchis",
    album: "Sin Miedo",
    duration: "2:40",
    bpm: 83,
    matchPercent: 84,
    mood: "romantic",
    accent: "#fbc2eb",
    secondaryAccent: "#a6c1ee",
  },
  {
    id: "instant-crush",
    title: "Instant Crush",
    artist: "Daft Punk",
    album: "Random Access Memories",
    duration: "5:37",
    bpm: 110,
    matchPercent: 79,
    mood: "focus",
    accent: "#ffe259",
    secondaryAccent: "#ffa751",
  },
];
